### PR TITLE
Lifting Swagger to OpenApi instances

### PR DESCRIPTION
**Pull request by ajuggler**
Thank you for contributing to Atlas! We appreciate your effort and dedication to improving this project. To ensure that your contribution is in line with the project's guidelines and can be reviewed efficiently, please fill out the template below.

Remember to follow our [Contributing Guide](CONTRIBUTING.md) before submitting your pull request.

## Summary

Please provide a brief, concise summary of the changes in your pull request. Explain the problem you are trying to solve and the solution you have implemented.

## Type of Change

Please mark the relevant option(s) for your pull request:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code refactoring (improving code quality without changing its behavior)
- [ ] Documentation update (adding or updating documentation related to the project)

## Checklist

Please ensure that your pull request meets the following criteria:

- [ ] I have read the [Contributing Guide](CONTRIBUTING.md)
- [ ] My code follows the project's coding style and best practices
- [ ] My code is appropriately commented and includes relevant documentation
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests pass
- [ ] I have updated the documentation, if necessary

## Testing

Please describe the tests you have added or modified, and provide any additional context or instructions needed to run the tests.

- [ ] Test A
- [ ] Test B

## Additional Information

If you have any additional information or context to provide, such as screenshots, relevant issues, or other details, please include them here.

### CODE REVIEW

**Comment by ajuggler** [comment]
Initial commit showcases examples of lifting instances from Swagger to OpenApi, using commands `swaggerToOpenApiSchema` and `convertNamedSchema`.  We use the former to lift a `ToSchema` Swagger instance when a `ToParamSchema` had also been defined.  We used the latter when this had not been the case.

**Comment by 4TT1L4** [comment]
Nice contribution! We really need the OpenAPI spec. Some code generators don't work with the legacy swagger API spec. This is a great update! Nice work!

**Comment by ajuggler** [comment]
Main functions are `swaggerToOpenApiSchema` and `swaggerToOpenApiSchema'`, exported by GeniusYield.Utils.

**Comment by ajuggler** [comment]
I gave up on adding field `additionalProperties` to function [`liftSwaggerSchema`](https://github.com/geniusyield/atlas/blob/7f06a38bb65f1ce96a1bc0dc649c1e5ac2aa0c8a/src/GeniusYield/Utils.hs#L77).  Instead, I added it directly to instance of `OpenApi.ToSchema` for `GYValue`, which apparently is the only datatype in Atlas that has it.

**Comment by ajuggler** [comment]
Added function [`printOpenApiSchema`](https://github.com/geniusyield/atlas/blob/7f06a38bb65f1ce96a1bc0dc649c1e5ac2aa0c8a/src/GeniusYield/Utils.hs#L103) to test manually:

```
ghci> -- Testing a datatype lifted with swaggerToOpenApiSchema'
ghci> 
ghci> :m GeniusYield.Types.TxOutRef 
ghci> import GeniusYield.Utils 
ghci> import Data.Proxy
ghci> 
ghci> printOpenApiSchema (Proxy @GYTxOutRef)
(fromList [],NamedSchema {_namedSchemaName = Just "GYTxOutRef", _namedSchemaSchema = Schema {_schemaTitle = Nothing, _schemaDescription = Nothing, _schemaRequired = [], _schemaNullable = Nothing, _schemaAllOf = Nothing, _schemaOneOf = Nothing, _schemaNot = Nothing, _schemaAnyOf = Nothing, _schemaProperties = fromList [], _schemaAdditionalProperties = Nothing, _schemaDiscriminator = Nothing, _schemaReadOnly = Nothing, _schemaWriteOnly = Nothing, _schemaXml = Nothing, _schemaExternalDocs = Nothing, _schemaExample = Nothing, _schemaDeprecated = Nothing, _schemaMaxProperties = Nothing, _schemaMinProperties = Nothing, _schemaDefault = Nothing, _schemaType = Just OpenApiString, _schemaFormat = Just "hex", _schemaItems = Nothing, _schemaMaximum = Nothing, _schemaExclusiveMaximum = Nothing, _schemaMinimum = Nothing, _schemaExclusiveMinimum = Nothing, _schemaMaxLength = Nothing, _schemaMinLength = Nothing, _schemaPattern = Just "[0-9a-fA-F]{64}#\"d+", _schemaMaxItems = Nothing, _schemaMinItems = Nothing, _schemaUniqueItems = Nothing, _schemaEnum = Nothing, _schemaMultipleOf = Nothing}})                                                                                                                                                           
ghci> 
ghci> 
ghci> -- Testing a datatype lifted with swaggerToOpenApiSchema
ghci> 
ghci> :m GeniusYield.Types.PaymentKeyHash 
ghci> import GeniusYield.Utils 
ghci> import Data.Proxy
ghci> 
ghci> printOpenApiSchema (Proxy @GYPaymentKeyHash)
(fromList [],NamedSchema {_namedSchemaName = Just "GYPaymentKeyHash", _namedSchemaSchema = Schema {_schemaTitle = Nothing, _schemaDescription = Just "The hash of a payment public key.", _schemaRequired = [], _schemaNullable = Nothing, _schemaAllOf = Nothing, _schemaOneOf = Nothing, _schemaNot = Nothing, _schemaAnyOf = Nothing, _schemaProperties = fromList [], _schemaAdditionalProperties = Nothing, _schemaDiscriminator = Nothing, _schemaReadOnly = Nothing, _schemaWriteOnly = Nothing, _schemaXml = Nothing, _schemaExternalDocs = Nothing, _schemaExample = Just (String "e1cbb80db89e292269aeb93ec15eb963dda5176b66949fe1c2a6a38d"), _schemaDeprecated = Nothing, _schemaMaxProperties = Nothing, _schemaMinProperties = Nothing, _schemaDefault = Nothing, _schemaType = Just OpenApiString, _schemaFormat = Just "hex", _schemaItems = Nothing, _schemaMaximum = Nothing, _schemaExclusiveMaximum = Nothing, _schemaMinimum = Nothing, _schemaExclusiveMinimum = Nothing, _schemaMaxLength = Just 56, _schemaMinLength = Just 56, _schemaPattern = Nothing, _schemaMaxItems = Nothing, _schemaMinItems = Nothing, _schemaUniqueItems = Nothing, _schemaEnum = Nothing, _schemaMultipleOf = Nothing}})                                                                          
ghci>
ghci>
ghci> -- Testing OpenApi.ToSchema of GYValue, which is special in that it lifts the field 'Swagger.additionalProperties'
ghci> 
ghci> :m GeniusYield.Types.Value
ghci> import GeniusYield.Utils
ghci> import Data.Proxy
ghci> 
ghci> printOpenApiSchema (Proxy @GYValue)
(fromList [],NamedSchema {_namedSchemaName = Just "GYValue", _namedSchemaSchema = Schema {_schemaTitle = Nothing, _schemaDescription = Just "A multi asset quantity, represented as map where each key represents an asset: policy ID and token name in hex concatenated by a dot.", _schemaRequired = [], _schemaNullable = Nothing, _schemaAllOf = Nothing, _schemaOneOf = Nothing, _schemaNot = Nothing, _schemaAnyOf = Nothing, _schemaProperties = fromList [], _schemaAdditionalProperties = Just (AdditionalPropertiesSchema (Inline (Schema {_schemaTitle = Nothing, _schemaDescription = Nothing, _schemaRequired = [], _schemaNullable = Nothing, _schemaAllOf = Nothing, _schemaOneOf = Nothing, _schemaNot = Nothing, _schemaAnyOf = Nothing, _schemaProperties = fromList [], _schemaAdditionalProperties = Nothing, _schemaDiscriminator = Nothing, _schemaReadOnly = Nothing, _schemaWriteOnly = Nothing, _schemaXml = Nothing, _schemaExternalDocs = Nothing, _schemaExample = Nothing, _schemaDeprecated = Nothing, _schemaMaxProperties = Nothing, _schemaMinProperties = Nothing, _schemaDefault = Nothing, _schemaType = Just OpenApiInteger, _schemaFormat = Nothing, _schemaItems = Nothing, _schemaMaximum = Nothing, _schemaExclusiveMaximum = Nothing, _schemaMinimum = Nothing, _schemaExclusiveMinimum = Nothing, _schemaMaxLength = Nothing, _schemaMinLength = Nothing, _schemaPattern = Nothing, _schemaMaxItems = Nothing, _schemaMinItems = Nothing, _schemaUniqueItems = Nothing, _schemaEnum = Nothing, _schemaMultipleOf = Nothing}))), _schemaDiscriminator = Nothing, _schemaReadOnly = Nothing, _schemaWriteOnly = Nothing, _schemaXml = Nothing, _schemaExternalDocs = Nothing, _schemaExample = Just (Object (fromList [("ff80aaaf03a273b8f5c558168dc0e2377eea810badbae6eceefc14ef.474f4c44",Number 101.0),("lovelace",Number 22.0)])), _schemaDeprecated = Nothing, _schemaMaxProperties = Nothing, _schemaMinProperties = Nothing, _schemaDefault = Nothing, _schemaType = Just OpenApiObject, _schemaFormat = Nothing, _schemaItems = Nothing, _schemaMaximum = Nothing, _schemaExclusiveMaximum = Nothing, _schemaMinimum = Nothing, _schemaExclusiveMinimum = Nothing, _schemaMaxLength = Nothing, _schemaMinLength = Nothing, _schemaPattern = Nothing, _schemaMaxItems = Nothing, _schemaMinItems = Nothing, _schemaUniqueItems = Nothing, _schemaEnum = Nothing, _schemaMultipleOf = Nothing}})
```

**Comment by ajuggler** [comment]
Moved the repl tests shown in previous comment to *doctests* added to files:  PaymentKeyHash.hs, TxOutRef.hs, and Value.hs.

**Comment by sourabhxyz** [comment]
Superseded by #308.

**Pull request closed without merging**
